sudo: false

language: node_js
node_js:
  - "lts/*"

install:
  - npm install

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: libero-npm@elifesciences.org
  api_key:
    secure: E7ZBx1yRrzwYvhrAeKun8a0CRCnNBoLLizA0M7odM31UkWGtakEu0PZZ+POdTjOuVeFejhk9q9pIRmTb8BkDgLZv+OC9hKSNQV6O14VNukCdcx2l8iSkfUrX9Ob9KYcFxdKjeGy+WswXr7kUihHQeYYF2I+tURRqDctCcpH3kpsUdt8+xnDxIDx2iB9tVGk0nmYAGr96zlTsf5M+0b65Z9lDknioWDm8+TkG1RKUWGvDpZ4lZgEGpajhAvxs5lLI2VJnR/SolhYU6imTU63B72vy0EsPb4PzhHi/2oHYuNft1LW0wRpioUB5MyD6BBI83SiLV7W1pyZ+7JW1sPUFa3sFMsHJJVxIq83p85l7ADn7N+nix5s1Ynhoho6i4lt3l+IjKKqbx9CU7kw1SdZgJVbFepOpMuw7mOxud5jhnXhY5W7R6LVjj/frKcekNgRq8hOe2d1Nk3drCOqaM1MVgPlxHoplhn0MiXhphzLWJQ8nGRt3jKZAAKynLbAJwqmYKxBt+QAAMDSo8UpeJaPauKAz9XaGHo9avF3pYP4nbHuCL1+AYt6ZHRvS4Qg9hrFVdDiDTRh3+Xzn5utu5pw5H0vWN6NjgeAMIWfGv1RDw23/xwuZOcMlxsr6ROtPWWZhyUyPBVQG8ViZ2nqePvz9e3cmINMR1zZkDrwtLsvzHq0=
  on:
    tags: true
    branch: master